### ISSUE TITLE
Use messense/rust-musl-cross as custom images in cross? [feature request]

### ISSUE THREAD

**Issue by xoac** [messense/rust-musl-cross#24]
Hi,
I was wondering about difference between [cross] and `messense/rust-musl-cross` images.
For sure there is big one - cross doesn't support openssl. Are there any other?

I am asking because maybe it would be good idea to make  `messense/rust-musl-cross` images work with cross.  See [custom docker images in cross](https://github.com/rust-embedded/cross/tree/47f325a73e5793a4b6d1bd61a482c533e1a0fa06#custom-docker-images).

[cross]:https://github.com/rust-embedded/cross

**Comment by messense** [comment]
Is it not working now? Could you paste the error message here?

**Comment by xoac** [comment]
➜ cross build --target armv7-unknown-linux-musleabihf
```
error: could not create home directory: '/.rustup'
error: caused by: Permission denied (os error 13)
```
➜ cat Cross.toml 
```
[target.armv7-unknown-linux-musleabihf]
image = "messense/rust-musl-cross:armv7-musleabihf"
```

**Comment by messense** [comment]
I think we need to find out what is trying to create the home directory `/.rustup`.

This issue might be somewhat related: https://github.com/rust-embedded/cross/issues/399
