### ISSUE TITLE
Months not shortened correctly on exa when compiled using messense/rust-musl-cross

### ISSUE THREAD

**Issue by eggbean** [messense/rust-musl-cross#26]
I think this issue where exa does not show the month August correctly may be because of it being compiled using messense/rust-musl-cross.

https://github.com/ogham/exa/issues/719

**Comment by messense** [comment]
exa hardcoded it to August I think.
https://github.com/ogham/exa/blob/78ba0b8973cbfbb48b85b8beae6f7de412064d11/src/output/time.rs#L140

**Comment by eggbean** [comment]
Ah okay, thanks. I thought it was the cross-compiler as it is only happening on the ARM build I am using. Seems fine on x86.
