### ISSUE TITLE
aarch64-unknown-linux-musl support

### ISSUE THREAD

**Issue by ginkel** [messense/rust-musl-cross#31]
Hi there,

in https://www.reddit.com/r/rust/comments/75u8qu/docker_images_for_compiling_static_rust_binaries/do97z5u you indicated that `aarch64-unknown-linux-musl` support may become available. Are there any news for this to share?

Thanks,
Thilo

**Comment by messense** [comment]
Added in https://github.com/messense/rust-musl-cross/commit/71cea641506b1f9cb9caaaab3df09b003275b9b0

```bash
docker pull messense/rust-musl-cross:aarch64-musl
```

**Comment by ginkel** [comment]
Excellent, thanks a lot!
