### ISSUE TITLE
cannot find value `SO_INCOMING_CPU` in crate `libc`

### ISSUE THREAD

**Issue by dosgo** [messense/rust-musl-cross#38]
![image](https://user-images.githubusercontent.com/9545458/123536350-67996000-d75c-11eb-92b2-c2569f3fd5cc.png)

docker run --rm --privileged=true -v /d/rust/ddnsv6-rust/src:/home/rust/src messense/rust-musl-cross:mipsel-musl  cargo build --release

**Comment by messense** [comment]
I think it's fixed in libc 0.2.93, see https://github.com/rust-lang/libc/pull/2135 , please check that the libc version in your `Cargo.lock` is new enough?

**Comment by messense** [comment]
https://github.com/dosgo/ddnsv6-rust/blob/0f08595e612796c2c8c9124d9b94ba65a28f1bdb/Cargo.lock#L888 it's `0.2.89`, you need to run `cargo update -p libc` to update it.

**Comment by dosgo** [comment]
OK, thank you very much.
