### ISSUE TITLE
Request To Add Prebuilt Docker Image For arm32v7 Architecture

### ISSUE THREAD

**Issue by aggo15** [messense/rust-musl-cross#43]
@messense is there any plan to add prebuild image of arm32v7 rust-musl-cross in the future?

I came across your docker image while trying to cross compile a rust source to target armv6, it got all the binaries I need. However due to my project requirements and some constraint on my work PC, I can only run my build on a Raspberry Pi 4 with 32bit OS. The prebuilt images available are only for arm64 and amd64 according to the repo on docker hub. 

Currently I'm working around this limitation by using official rust arm32v7 image and run `make install` for musl-cross-make on the image. It would be great if you can add arm32v7 prebuilt image as it will result in lesser complexity of my Dockerfile for my project.

Thank you in advance.

**Comment by messense** [comment]
By arm32v7 I assume you mean the `armv7-unknown-linux-musleabihf` or `armv7-unknown-linux-musleabi` Rust target? They exist already: https://github.com/messense/rust-musl-cross#prebuilt-images

**Comment by messense** [comment]
Hmm I think you mean you want the arm32v7 docker image architecture not the Rust target, we don't have that yet, it'd need a suitable GitHub Actions self-hosted runner which I don't have right now.

**Comment by aggo15** [comment]
@messense yes you are right I meant the arm32v7 docker image architecture. Hopefully you will add that in the future. 

Thank you.

**Comment by jld-adriano** [comment]
https://hub.docker.com/r/joaonortech/rust-multiarch/tags Temporarily built these for internal use, the same but as a multi architecture docker manifest, including armv7
