### ISSUE TITLE
Add env for compile openssl

### ISSUE THREAD

**Issue by zydxhs** [messense/rust-musl-cross#49]
I cross-compiled the openssl library using `messense/rust-musl-cross: aaarch64-musl` and had to manually modify the following environment variables:

- `export TARGET=x86_64-unknown-linux-musl`
- `export CC=$TARGET_CC`
- `export C_INCLUDE_PATH=$TARGET_C_INCLUDE_PATH`
- `export LD=$TARGET-ld`

Why not add them to the environment variables of the docker image?

**Comment by messense** [comment]
https://github.com/messense/rust-musl-cross/issues/35#issue-881628375

TLDR: use openssl-src crate instead.

**Comment by zydxhs** [comment]
It took me a long time to finally figure out how to use OpenSSL-sys.
