### ISSUE TITLE
GH Actions notifications on cloned repo

### ISSUE THREAD

**Issue by paulwratt** [messense/rust-musl-cross#52]
I just updated the `master` branch on my repo, and now I have failed Action Notifications in my mail box

How can I stop that without making a commit to delete it (which will be questioned next time I update the branch) (EDIT: and makes making PR's a bit problematic).

NOTE: I was _not_ getting any Actions or Notifications before that (then 53 commits behind _I think_ )

**Comment by messense** [comment]
Self-hosted runners are now disabled on forks: https://github.com/messense/rust-musl-cross/commit/771d24c388c9c58f5c09e789657c05b064ae7f37

**Comment by paulwratt** [comment]
sweet thanks @messense

**Comment by messense** [comment]
Fixed the docker login/push issue in https://github.com/messense/rust-musl-cross/commit/7f2c43bdb6db4c28fcb11fcd9869999a272738b2
