### ISSUE TITLE
`messense/rust-musl-cross:x86_64-musl` is not `x86_64-unknown-linux-musl` target.

### ISSUE THREAD

**Issue by mokeyish** [messense/rust-musl-cross#71]
Thanks for your work on this. A very usefull docker image to build musl target.

But recently, I find that `messense/rust-musl-cross:x86_64-musl` is not `x86_64-unknown-linux-musl` target. It shows `x86_64-unknown-linux-gun` in my wsl2 kali  roling linux.

**Comment by messense** [comment]
> It shows `x86_64-unknown-linux-gun` in my wsl2 kali roling linux.

What do you mean by this? **What** show that? Can you give a list of steps to reproduce?

**Comment by mokeyish** [comment]
@messense 

It can reproduce by following steps:

1. create command alias
    ```shell
    alias rust-musl-builder='mkdir -p .cargo/registry && mkdir -p .cargo/git  && podman run -it -v "$(pwd)/.cargo/registry":/root/.cargo/registry -v "$(pwd)/.cargo/git":/root/.cargo/git -v "$(pwd)":/home/rust/src messense/rust-musl-cross:x86_64-musl'
    ```
2. run  command `rust-musl-builder`
3. list toolchains
   
<img width="827" alt="图片" src="https://user-images.githubusercontent.com/16131917/195812811-4ed68c61-a6cc-439f-b3f0-11cb6e05db74.png">


   ```

**Comment by messense** [comment]
I think you misunderstood the difference between `toolchain` and `target`.

* https://rust-lang.github.io/rustup/concepts/toolchains.html
* https://rust-lang.github.io/rustup/cross-compilation.html

**Comment by mokeyish** [comment]
Thanks!
