### ISSUE TITLE
aarch64-musl crashing when building app

### ISSUE THREAD

**Issue by Ludea** [messense/rust-musl-cross#75]
Hi,

I try to build a rust app with musl, by rust-mul-cross images and GHA.

x86_64 works fine, but aarch64 crash.

I get:
```> [alpine-builder-aarch64 5/5] RUN cargo build --release:
#14 5.127     Updating crates.io index
#14 85.51 Killed
ERROR: failed to solve: process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 137
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c cargo build --release" did not complete successfully: exit code: 137
```

GHA Workflow: https://github.com/Ludea/speedupdate-rs/blob/master/.github/workflows/docker.yml
Dockerfile: https://github.com/Ludea/speedupdate-rs/blob/master/Dockerfile
Full log: https://github.com/Ludea/speedupdate-rs/actions/runs/3409830963/jobs/5672075085

I don't understand what is wrong

**Comment by messense** [comment]
Try add `CARGO_NET_GIT_FETCH_WITH_CLI=true`, probably related to `libgit2`, see https://github.com/rust-lang/cargo/issues/10583

**Comment by Ludea** [comment]
Works as expected, thanks !
Maybe you could add a note into Readme.md ?

**Comment by messense** [comment]
IMO you don't need QEMU, you can just cross compile aarch64 target, for example https://github.com/PyO3/maturin/blob/cb0b6c6d39777952e7e22e3e88dff61b5b7c3edb/Dockerfile#L1-L9

See also https://www.docker.com/blog/cross-compiling-rust-code-for-multiple-architectures/
