### ISSUE TITLE
Building diesel/postgres

### ISSUE THREAD

**Issue by Edu4rdSHL** [messense/rust-musl-cross#76]
Hello, great job. Question, this crate aims to be "inspired by [rust-musl-builder](https://github.com/emk/rust-musl-builder)" but I didn't see an option to build [Diesel/postgress-based](https://github.com/emk/rust-musl-builder#making-diesel-work) apps which is quite the point of emk/rust-musl-builder. Am I missing something?

I have tried to build a Diesel app using it and doesn't work.

**Comment by messense** [comment]
This project is focused on cross compiling, so we don't provide prebuilt C/C++ libraries.
