### ISSUE TITLE
Strip

### ISSUE THREAD

**Issue by xoac** [messense/rust-musl-cross#9]
Hi,
I was wondering how I could cross strip my final application just using this docker image? Anybody know about existing cross striping? or maybe some `[profile.release]` configuration (can rustc strip by itself?)

**Comment by dbrgn** [comment]
I'd also be interested in a strip option 🙂

**Comment by messense** [comment]
Sorry for late response. I think musl comes with `strip` command prefix with target name, for example `x86_64-linux-musl-strip`, you can use it to strip binary.

**Comment by JimChenWYU** [comment]
hello, how can I to know what different between `musl-strip` and `strip`(from [GNU Binary Utilities](https://sourceware.org/binutils/docs/binutils/strip.html))?
